#!perl
use strict;
use warnings;
use Capture::Tiny qw(capture_stdout);

my $struct_to_hash = "author_tools/struct_to_hash.pl";
my $outfile = "src/perl_conversion_functions.h";

print "Writing output to file '$outfile'.\n";

open my $fh, ">", $outfile or die $!;
print $fh <<"HERE";
#ifndef PERL_CONVERSION_FUNCTIONS_H_
#define PERL_CONVERSION_FUNCTIONS_H_

/* WARNING!
 * This code is autogenerated. Have a look at author_tools/regen.pl and
 * its friend author_tools/struct_to_hash.pl!
 */

#include <EXTERN.h>
#include <perl.h>

/* used by the real_1d_array typemap, but also usable separately */
AV *
real_1d_array_to_av(pTHX_ const alglib::real_1d_array &x)
{
  const unsigned int len = x.length();
  AV *av = newAV();
  unsigned int i;
  av_extend(av, len-1);
  for (i = 0; i < len; ++i)
    av_store(av, i, newSVnv(x[i]));
  return av;
}

/* used by integration.h to return an array of a status int
 * followed by two real_1d_array's */
AV *
integration_return_status_ary_ary(pTHX_ IV info,
                                  const alglib::real_1d_array &x,
                                  const alglib::real_1d_array &w)
{
  AV *av = newAV();
  av_extend(av, 2);
  av_store(av, 0, newSViv(info));
  av_store(av, 1, newRV_noinc((SV *) real_1d_array_to_av(aTHX_ x)));
  av_store(av, 2, newRV_noinc((SV *) real_1d_array_to_av(aTHX_ w)));
  return av;
}


HERE

my $typemap = "xsp/mytype.map";
my $functions = [
#  {
#    file => "src/diffequations.h",
#    struct_name => "odesolverstate",
#    struct_fq => "alglib_impl::odesolverstate",
#    c_to_perl_function => "odesolverstate_to_perl_hash",
#  },
];

# emit header include
foreach my $func (@$functions) {
  my $header = $func->{file};
  $header =~ s/^src\///; # FIXME hack
  print $fh "#include <$header>\n";
}

print $fh "\nusing namespace alglib; /* FIXME hack */\n\n";

# emit function bodies
foreach my $func (@$functions) {
  my @cmd = (
    $^X,
    $struct_to_hash,
    "--typemap", $typemap,
    (map {("--$_", $func->{$_})} keys %$func)
  );

  print "Regenerating function '$func->{c_to_perl_function}' from struct '$func->{struct_name}' in '$func->{file}'...\n";
  my $stdout = capture_stdout {
    system(@cmd) and die "Failed to run '@cmd': $!";
  };

  #print $fh "\n#line 1 \"@cmd\"\n";
  print $fh $stdout;
}

print $fh <<HERE;

#endif
HERE

