#ifndef PERL_CONVERSION_FUNCTIONS_H_
#define PERL_CONVERSION_FUNCTIONS_H_

/* WARNING!
 * This code is autogenerated. Have a look at author_tools/regen.pl and
 * its friend author_tools/struct_to_hash.pl!
 */

#include <EXTERN.h>
#include <perl.h>

AV *
real_1d_array_to_av(pTHX_ const alglib::real_1d_array &x) {
  const unsigned int len = x.length();
  AV *av = newAV();
  unsigned int i;
  av_extend(av, len-1);
  for (i = 0; i < len; ++i)
    av_store(av, i, newSVnv(x[i]));
  return av;
}


using namespace alglib; /* FIXME hack */


#endif
